apiVersion: apps/v1
kind: Deployment
metadata:
  name: similarity
  labels:
    app: similarity
spec:
  replicas: 1
  selector:
    matchLabels:
      app: similarity
  template:
    metadata:
      labels:
        app: similarity
    spec:
      containers:
        - name: similarity
          image: asia-south1-docker.pkg.dev/PROJECT/containers/similarity:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
          env:
            - name: PORT
              value: "5000"
            - name: AI_SCORE_API_URL
              value: "http://ai-content-svc"
          readinessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 15
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 45
            periodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: similarity-svc
  labels:
    app: similarity
spec:
  selector:
    app: similarity
  ports:
    - name: http
      port: 80
      targetPort: 5000
  type: LoadBalancer
